# Generated by Django 6.0.3 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrivalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('image_url', models.FileField(default=None, null=True, upload_to='NewArrivalsProductsImages')),
                ('imgVariant1', models.FileField(default=None, null=True, upload_to='NewArrivalsProductsImages')),
                ('imgVariant2', models.FileField(default=None, null=True, upload_to='NewArrivalsProductsImages')),
                ('oldPrice', models.CharField()),
                ('newPrice', models.CharField()),
            ],
        ),
    ]
