# Generated by Django 6.0.3 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_categoryproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproducts',
            name='height1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='left1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='left2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='peding1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='top1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='top2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='width1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoryproducts',
            name='width2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
