# Generated by Django 6.0.3 on 2026-04-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categoryproducts_height1_categoryproducts_left1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrendingImage', models.FileField(upload_to='')),
                ('TrendingTitle', models.TextField()),
                ('TrendingDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Videolink', models.FileField(upload_to='PromotionSection/videos/')),
                ('ImageLink', models.FileField(upload_to='PromotionSection/images/')),
                ('Name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
            ],
        ),
    ]
