# Generated by Django 6.0.3 on 2026-04-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_articles_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='TrendingImage',
            field=models.FileField(upload_to='PromotionSection/images/'),
        ),
    ]
