# Generated by Django 6.0.3 on 2026-04-02 19:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_articles_trendingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='TrendingImage',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='ImageLink',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Videolink',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
