# Generated by Django 6.0.3 on 2026-04-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_articles_trendingimage_alter_videos_imagelink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarrivalproducts',
            name='image_url',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newarrivalproducts',
            name='imgVariant1',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newarrivalproducts',
            name='imgVariant2',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
