# Generated by Django 6.0.3 on 2026-04-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_newarrivalproducts_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproducts',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
