# Generated by Django 6.0.3 on 2026-04-03 22:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_categoryproducts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10)),
            ],
        ),
    ]
