"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# This line loads the passwords from your .env file!
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "ronin-pk-landing-page-clone-production.up.railway.app"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'products',
    'users.apps.UsersConfig',
    'django.contrib.sites',  # REQUIRED by allauth

    
    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Social Providers you want to use
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',

    'widget_tweaks',
    'axes',
]

# If a user logs in with Facebook, and their email already exists in our database,
# automatically connect their Facebook to their existing account!
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True



# Required for allauth to know which site it's working on
SITE_ID = 1 

AUTH_USER_MODEL = 'users.CustomUser'

LOGIN_URL = 'login'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend', # <--- Must be at the top!
    'django.contrib.auth.backends.ModelBackend', # Needed to login by username in Django admin
    'allauth.account.auth_backends.AuthenticationBackend', # `allauth` specific authentication methods
]

SOCIALACCOUNT_LOGIN_ON_GET = True # Skips the "Are you sure you want to login?" intermediate page

CORS_ALLOWED_ORIGINS = [
    "https://ronin-pk-landing-page-clone.vercel.app",
]
CORS_ALLOW_CREDENTIALS = True  # ADD THIS! It allows the frontend to send session cookies.

# Tell Django that your Vite frontend is completely safe for POST requests
CSRF_TRUSTED_ORIGINS = [
    "https://ronin-pk-landing-page-clone.vercel.app",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # UPDATE THIS LINE:
        'DIRS': [os.path.join(BASE_DIR, '../frontend')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# This tells WhiteNoise to compress and cache the files for better performance
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_ROOT = BASE_DIR / "media"

MEDIA_URL = "/media/"

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'wick25315@gmail.com'
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')


# ---------------------------------------------------------
# DJANGO-ALLAUTH SOCIAL LOGIN REDIRECT SETTINGS
# ---------------------------------------------------------

# 1. Where to send the user immediately after a successful login
LOGIN_REDIRECT_URL = 'https://ronin-pk-landing-page-clone.vercel.app/profile.html'

# 2. Where to send the user after they log out
ACCOUNT_LOGOUT_REDIRECT_URL = 'https://ronin-pk-landing-page-clone.vercel.app/login.html'

# 3. Skip the intermediate "Are you sure you want to sign in?" black/white screen
SOCIALACCOUNT_LOGIN_ON_GET = True

# 4. Automatically create the user's account without asking them to fill out a form
SOCIALACCOUNT_AUTO_SIGNUP = True

# 5. (Optional but recommended) Don't send emails to social login users asking them to confirm
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none' 


# Force allauth to ask Google for the email
SOCIALACCOUNT_QUERY_EMAIL = True

# 2. Require an email and username for all accounts (The '*' means required)
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']

# 1. Allow login with EITHER username or email
ACCOUNT_LOGIN_METHODS = {'email', 'username'}



# ==========================================
# DJANGO-AXES (BRUTE FORCE PROTECTION)
# ==========================================

# 1. How many failed logins before they get blocked?
AXES_FAILURE_LIMIT = 5

# 2. How long should they be blocked? (In hours. 0.25 = 15 minutes)
AXES_COOLOFF_TIME = 0.25

# 3. Block them based on their IP Address
AXES_LOCKOUT_PARAMETERS = ["ip_address"]

# 4. (Optional) Reset the failed attempts to 0 if they successfully log in
AXES_RESET_ON_SUCCESS = True

CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT is disabled — Railway's edge layer handles SSL termination
# and re-enabling this would cause infinite redirect loops behind the proxy.
SECURE_SSL_REDIRECT = False


# CELERY SETTINGS
# Use the CELERY_BROKER_URL env var when Redis is available (e.g. a Railway Redis
# service).  Falls back to the in-memory transport so the app starts cleanly in
# environments where Redis has not been provisioned yet.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'memory://')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'